name: Fiery
main: me.herghost.Fiery.Fiery
author: Dave@MinecraftClan.com
website: http://www.minecraftclan.com
description: Multi use plugin for MinecraftClan.com Servers
version: 0.1

commands:
         item:
               description: Give Items to Yourself
               permission: Fiery.admin.item
               usage: /item (amount) (item)
         give:
               description: Give Items to Others
               permission: Fiery.admin.give
               usage: /give (player) (item) (amount)
         kick:
               description: Kick Player
               permission: Fiery.admin.kick
               usage: /kick (player) (reason)
         ban:
               description: Ban Player
               permission: Fiery.admin.ban
               usage: /ban (player)
         unban:
               description: Unban a banned player
               permission: Fiery.admin.unban
               usage: /unban (player)
         op:
               description: Op an Player
               permission: Fiery.admin.op
               usage: /op playername
         deop:
               description: Un-Op an Player
               permission: Fiery.admin.deop
               usage: /deop playername
         gamemode:
              description: Change gamemode
              permission: Fiery.admin.gamemode
              usage: /game (player) (1,0)
         doreload:
              description: Allows non mods to reload server
              permission: Fiery.admin.doreload
              usage: /doreload
         spawn:
               description: Return to Spawn
               permission: Fiery.spawn
               usage: /spawn
         
         sethome:
               description: Choose upto 3 homes
               permission: Fiery.sethome
               usage: /sethome (blank, 1 or 2)
         home:
               description: Go Home
               permission: Fiery.home
               usage: /home (blank, 1 or 2)
         money:
               description: Shows Balance
               permission: Fiery.money
               usage: /money
         settime:
              description: Sets Time
              permission: Fiery.setTime
              usage: /settime day/night
         
               
             