name: Fiery
main: me.herghost.Fiery.Fiery
author: Dave@MinecraftClan.com
website: http://www.minecraftclan.com
description: Multi use plugin for MinecraftClan.com Servers
version: 0.1

commands:
         item:
               description: Give Items to Yourself
               permission: Fiery.admin.item
               usage: /item (id) (amount)
         give:
               description: Give Items to Others
               permission: Fiery.admin.give
               usage: /give (player) (item) (amount)
         kick:
               description: Kick Player
               permission: Fiery.admin.kick
               usage: /kick (player) (reason)
         spawn:
               description: Return to Spawn
               permission: Fiery.spawn
               usage: /spawn
         ban:
               description: Ban Player
               permission: Fiery.admin.ban
               usage: /ban (player)
         unban:
               description: Unban a banned player
               permission: Fiery.admin.unban
               usage: /unban (player)
         sethome:
               description: Choose upto 3 homes
               permission: Fiery.sethome
               usage: /sethome (blank, 1 or 2)
         home:
               description: Go Home
               permission: Fiery.home
               usage: /home (blank, 1 or 2)
         mop:
               description: Op an Player
               permission: Fiery.admin.mop
               usage: /mop playername
         rmop:
               description: Un-Op an Player
               permission: Fiery.admin.rmop
               usage: /rmop playername
               
             